### ISSUE TITLE
CKAN not showing comp[atible with current version

### ISSUE THREAD

**Issue by linuxgurugamer** [ArchLinus/WASDForVAB#2]
If it's comp-atibe, can you get CKAN up-dated

**Comment by ArchLinus** [comment]
Apologies but I've lost interest in KSP 2 :(

I recognize you as the creator of the WASD plugin for the KSP 1. Would you be interested in taking over this project?

**Comment by TryTryAgain** [comment]
@linuxgurugamer ... never too early to start resurrecting useful but forgotten KSP2 mods ;)

I can confirm it's not working for me, if I can help debug I'd be happy to...would just need to learn how first.

**Comment by linuxgurugamer** [comment]
> Apologies but I've lost interest in KSP 2 :(
> 
> I recognize you as the creator of the WASD plugin for the KSP 1. Would you be interested in taking over this project?

I'll be happy to.  It was working the last time I looked, but I'll look into it in a day or so

**Comment by linuxgurugamer** [comment]
> @linuxgurugamer ... never too early to start resurrecting useful but forgotten KSP2 mods ;)
> 
> I can confirm it's not working for me, if I can help debug I'd be happy to...would just need to learn how first.

Are you sure it's not working?  I know that CKAN doesn't think it's compatible, but if you tell CKAN to install mods compatible with 0.1 (Settings->Compatible Game Versions), then it installs and works for me.

There is one small change I want to make to the mod (making the wasd default to active instead of inactive), but other than that, it seems to be ok.  I've created a new repo here:  https://github.com/linuxgurugamer/WASDForVAB  to do the development, please move any more comments there so that I'll see them

**Comment by TryTryAgain** [comment]
You are right, thank you for pointing that out...I didn't realize/see https://github.com/ArchLinus/WASDForVAB/issues/3 ... I had installed it via ckan with 'is:compatible" removed so looks like it just needs a ckan update for now  :) ... "making the wasd default to active instead of inactive" ... great improvement. Thanks again @linuxgurugamer ... always grateful/impressed with what you pull off!
